INSERT INTO DEMO.T_CUST( CUST_NAME) VALUES ('DIPANJAN SENGUPTA');

INSERT INTO DEMO.T_ACCT_TYPE(ACCT_TYPE_DESC) VALUES ( 'SAVINGS');
INSERT INTO DEMO.T_ACCT_TYPE(ACCT_TYPE_DESC) VALUES ( 'MORTGAGE');
INSERT INTO DEMO.T_ACCT_TYPE(ACCT_TYPE_DESC) VALUES ( 'CREDIT');

INSERT INTO DEMO.T_TXFR_TYPE( TXFR_TYPE_DESC) VALUES ( 'SELF-PAY');
INSERT INTO DEMO.T_TXFR_TYPE( TXFR_TYPE_DESC) VALUES ( 'BILL-PAY');
INSERT INTO DEMO.T_TXFR_TYPE( TXFR_TYPE_DESC) VALUES ( 'SURE-PAY');

INSERT INTO DEMO.T_TXFR_SCHD_FRQ(TXFR_SCHD_FRQ_DESC) VALUES ( 'WEEKLY');
INSERT INTO DEMO.T_TXFR_SCHD_FRQ(TXFR_SCHD_FRQ_DESC) VALUES ( 'BIMONTHLY');
INSERT INTO DEMO.T_TXFR_SCHD_FRQ(TXFR_SCHD_FRQ_DESC) VALUES ( 'LAST FRIDAY OF MONTH');
INSERT INTO DEMO.T_TXFR_SCHD_FRQ(TXFR_SCHD_FRQ_DESC) VALUES ('MONTHLY');
INSERT INTO DEMO.T_TXFR_SCHD_FRQ(TXFR_SCHD_FRQ_DESC) VALUES ( 'QUARTERLY');
INSERT INTO DEMO.T_TXFR_SCHD_FRQ(TXFR_SCHD_FRQ_DESC) VALUES ( 'YEARLY');

INSERT INTO DEMO.T_ACCT_TXN_TYPE(ACCT_TXN_TYPE_DESC) VALUES ( 'DEBIT');
INSERT INTO DEMO.T_ACCT_TXN_TYPE(ACCT_TXN_TYPE_DESC) VALUES ( 'CREDIT');

INSERT INTO DEMO.T_ACCT_TXN_SUBTYPE( ACCT_TXN_TYPE_ID,ACCT_TXN_SUBTYPE_DESC) VALUES ( 100,'SCHEDULED');
INSERT INTO DEMO.T_ACCT_TXN_SUBTYPE( ACCT_TXN_TYPE_ID,ACCT_TXN_SUBTYPE_DESC) VALUES ( 100,'NON-SCHEDULED');
INSERT INTO DEMO.T_ACCT_TXN_SUBTYPE( ACCT_TXN_TYPE_ID,ACCT_TXN_SUBTYPE_DESC) VALUES ( 101,'SCHEDULED');
INSERT INTO DEMO.T_ACCT_TXN_SUBTYPE( ACCT_TXN_TYPE_ID,ACCT_TXN_SUBTYPE_DESC) VALUES ( 101,'NON-SCHEDULED');

INSERT INTO `DEMO`.`T_ACCT`(`ACCT_NO`,`CUST_ID`,`ACCT_TYPE_ID`,`ACCT_ALLW_SCHD_TXN`)VALUES('S00000',300,600,'Y');
INSERT INTO `DEMO`.`T_ACCT`(`ACCT_NO`,`CUST_ID`,`ACCT_TYPE_ID`,`ACCT_ALLW_SCHD_TXN`)VALUES('S00001',300,600,'N');
INSERT INTO `DEMO`.`T_ACCT`(`ACCT_NO`,`CUST_ID`,`ACCT_TYPE_ID`,`ACCT_ALLW_SCHD_TXN`)VALUES('M00000',300,601,'Y');
INSERT INTO `DEMO`.`T_ACCT`(`ACCT_NO`,`CUST_ID`,`ACCT_TYPE_ID`,`ACCT_ALLW_SCHD_TXN`)VALUES('M00001',300,601,'N');
INSERT INTO `DEMO`.`T_ACCT`(`ACCT_NO`,`CUST_ID`,`ACCT_TYPE_ID`,`ACCT_ALLW_SCHD_TXN`)VALUES('C00000',300,602,'Y');
INSERT INTO `DEMO`.`T_ACCT`(`ACCT_NO`,`CUST_ID`,`ACCT_TYPE_ID`,`ACCT_ALLW_SCHD_TXN`)VALUES('C00001',300,602,'N');

INSERT INTO `DEMO`.`T_ACCT_TXN`(`ACCT_TXN_SUBTYPE_ID`,`ACCT_ID`,`ACCT_TXN_AMT`)VALUES(200,700,1000);
INSERT INTO `DEMO`.`T_ACCT_TXN`(`ACCT_TXN_SUBTYPE_ID`,`ACCT_ID`,`ACCT_TXN_AMT`)VALUES(201,701,1000);
INSERT INTO `DEMO`.`T_ACCT_TXN`(`ACCT_TXN_SUBTYPE_ID`,`ACCT_ID`,`ACCT_TXN_AMT`)VALUES(202,700,1000);
INSERT INTO `DEMO`.`T_ACCT_TXN`(`ACCT_TXN_SUBTYPE_ID`,`ACCT_ID`,`ACCT_TXN_AMT`)VALUES(203,701,1000);
INSERT INTO `DEMO`.`T_ACCT_TXN`(`ACCT_TXN_SUBTYPE_ID`,`ACCT_ID`,`ACCT_TXN_AMT`)VALUES(200,702,1000);
INSERT INTO `DEMO`.`T_ACCT_TXN`(`ACCT_TXN_SUBTYPE_ID`,`ACCT_ID`,`ACCT_TXN_AMT`)VALUES(201,703,1000);
INSERT INTO `DEMO`.`T_ACCT_TXN`(`ACCT_TXN_SUBTYPE_ID`,`ACCT_ID`,`ACCT_TXN_AMT`)VALUES(202,702,1000);
INSERT INTO `DEMO`.`T_ACCT_TXN`(`ACCT_TXN_SUBTYPE_ID`,`ACCT_ID`,`ACCT_TXN_AMT`)VALUES(203,703,1000);
INSERT INTO `DEMO`.`T_ACCT_TXN`(`ACCT_TXN_SUBTYPE_ID`,`ACCT_ID`,`ACCT_TXN_AMT`)VALUES(200,704,1000);
INSERT INTO `DEMO`.`T_ACCT_TXN`(`ACCT_TXN_SUBTYPE_ID`,`ACCT_ID`,`ACCT_TXN_AMT`)VALUES(201,705,1000);
INSERT INTO `DEMO`.`T_ACCT_TXN`(`ACCT_TXN_SUBTYPE_ID`,`ACCT_ID`,`ACCT_TXN_AMT`)VALUES(202,704,1000);
INSERT INTO `DEMO`.`T_ACCT_TXN`(`ACCT_TXN_SUBTYPE_ID`,`ACCT_ID`,`ACCT_TXN_AMT`)VALUES(203,705,1000);